Rails.application.routes.draw do
  # Routes for agent_tasks generated by controller generator
  resources :agent_tasks, only: [:index, :show]
  # End routes for agent_tasks

  # Routes for command_executions generated by controller generator
  resources :command_executions, only: [:index, :show]
  # End routes for command_executions

  # Routes for coding_files generated by controller generator
  resources :coding_files, only: [:index, :show] do
    resources :file_versions, only: [:index, :create]
  end
  resources :file_versions, only: [:show]
  # End routes for coding_files

  # Routes for projects generated by controller generator
  resources :projects, only: [:index, :show, :create]
  # End routes for projects

  # Routes for conversations generated by controller generator
  resources :conversations, only: [:index, :show, :create]
  # End routes for conversations

  # write your business logic routes here

  # API routes
  namespace :api do
    namespace :v1 do
      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage')
    }
end
